[visionflow]
MONGO_URI = mongodb://localhost:27017/
UPLOAD_DIR = c:\Users\Anish\Desktop\Vision flow\Datasetlab\storage\uploads
DATASET_DIR = c:\Users\Anish\Desktop\Vision flow\Datasetlab\storage\datasets
YOLO_MODEL_PATH = c:\Users\Anish\Desktop\Vision flow\Datasetlab\yolov8s-world.pt
PORT_DATASET_SERVICE = 5003
PORT_PROJECT_SERVICE = 5004
PORT_INFERENCE_SERVICE = 5006
PORT_AUTH_SERVICE = 5001
API_GATEWAY_URL = http://localhost:8000
SECRET_KEY = dev-secret-key-123
